# Generated by Django 3.0.1 on 2020-02-07 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='liked_ny',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
