# Generated by Django 3.0.1 on 2020-02-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_ques_liked_ny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques',
            old_name='liked_ny',
            new_name='liked_by',
        ),
    ]
